---
title: "Aula 01: Modelo Bernoulli"
author: "Prof. Dr. Eder Angelo Milani"
date: "12/05/2023"
output: 
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modelo Bernoulli

Objetivo: estimar a proporção de "sucesso" em uma amostra aleatória, de tamanho $n$, de ensaios de Bernoulli.

Parâmetro: $\theta$ é proporção de "sucesso" na propulação

Modelo: $P(X=x|\theta) = \frac{n!}{x!(n-x)!} \theta^x(1-\theta)^{n-x}$


Distribuição à priori: Como o espaço paramétrico é igual ao intervalo unitário, a distribuição que resume o conhecimento à priori do pesquisador tem que ter o mesmo suporte do espaço paramétrico.  


# Opção 1 -  Distribuição à Priori Uniforme

Utilizando o teorema de Bayes, tem-se que 

$$h(\theta| x) \propto l(x|\theta)h(\theta) = \theta^{x}(1 - \theta)^{n - x}h(\theta)$$  
note que $l(\theta| x) = f(x | \theta)$. 

Do fato que $h(\theta)$ é a distribuição uniforme no intervalo $(0, 1)$, tem-se que 


$$\theta|x \sim Beta(x+1, n-x+1),$$  
sendo que $x$ representa uma observação do modelo Binomial.


**Exercício 1** Adote que 

-a. $n = 4$ e $x = 3$;

-b. $n = 12$ e $x = 9$;

-c. $n = 60$ e $x = 45$;

-d. $n = 100$ e $x = 75$.


Faça um plot com a distribuição à priori e com a respectiva distribuição a posteriori. Calcule em cada caso a média da distribuição a posteriori. 


Obs.: note que a razão $x/n$ é sempre igual a 0,75, ou seja, o estimador de máxima verossimilhança é sempre igual a 0,75.   


**Solução**


# Opção 2 -  Distribuição à Priori Beta($\alpha, \beta$)


A função densidade da distribuição Beta($\alpha, \beta$) é dada por 

$f(x) = \frac{\Gamma(\alpha+\beta)}{\Gamma(\alpha)\Gamma(\beta)}x^{\alpha-1}(1-x)^{\beta-1}$

Utilizando o teorema de Bayes, tem-se que 

$$h(\theta| x) \propto l(x|\theta)h(\theta) = \theta^{x}(1 - \theta)^{n - x}\theta^{\alpha-1}(1-\theta)^{\beta-1}$$  
note que $l(\theta| x) = f(x | \theta)$. Logo, $$\theta|x \sim Beta(x+\alpha, n-x+\beta),$$  
sendo que $x$ representa uma observação do modelo Binomial.


**Exercício 2** Adote que $n = 12$, $x = 9$ e 

-a. $\alpha = 1, \beta = 1$;

-b. $\alpha = 5, \beta = 5$;

-c. $\alpha = 20, \beta = 20$;

-d. $\alpha = 50, \beta = 50$.


Faça um plot com a distribuição a priori e com a respectiva distribuição a posteriori. Calcule também a média da distribuição à posteriori.


Obs.: note que em todos os cenários a média da distribuição à priori é sempre igual a 0,5. 


**Solução**